version: "3.8"
services:
  web:
    build: .
    ports:
      - "8090:8090"
    environment:
      - PORT=8090
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
    depends_on:
      - redis
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
  
  test:
    build: .
    depends_on:
      - web
      - redis
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - PORT=8090
    command: ["sh", "-c", "go test -v"]
  
volumes:
  redis-data: